name: Test Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Copy .env.test to .env
        working-directory: src
        run: cp backend/app/.env.test .env

      - name: Build
        working-directory: src
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml build

      - name: Down
        working-directory: src
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml down -v --remove-orphans

      - name: Up
        working-directory: src
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml up -d --wait backend db opensearch

      - name: Show container status
        if: always()
        working-directory: src
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml ps -a

      - name: Show backend logs on failure
        if: failure()
        working-directory: src
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml logs backend

      - name: Show database logs on failure
        if: failure()
        working-directory: src
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml logs db

      - name: Show opensearch logs on failure
        if: failure()
        working-directory: src
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml logs opensearch

      - name: Test backend is up
        working-directory: src
        run: curl http://localhost:8081/api/v1/utils/health-check

      - name: Down
        if: always()
        working-directory: src
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml down -v --remove-orphans